import { describe,expect,it } from "vitest";import { aggregateLeaderboard,appearanceRating,uniqueWinningTeamId } from "./rating";import type { FootballSession } from "@/types/domain";
const session=(wins:number[],format:FootballSession["format"]="sets"):FootballSession=>({id:"s",clientSessionId:"c",kickoffAt:"2026-09-01T17:00:00Z",format,teams:wins.map((setWins,i)=>({id:`t${i}`,label:`T${i}`,setWins})),appearances:[{playerId:"a",playerName:"Alpha",teamId:format==="none"?undefined:"t0",goals:0,assists:0},{playerId:"b",playerName:"Beta",teamId:format==="none"?undefined:"t1",goals:0,assists:0}]});
it("keeps competition ranks for three-way ties at the top and further down", () => {
  const s = session([], "none");
  s.appearances = [3, 3, 3, 2, 2, 2, 1].map((goals, index) => ({ playerId: String(index), playerName: `Player ${index}`, goals, assists: 0 }));
  expect(aggregateLeaderboard([s]).map(row => row.rank)).toEqual([1, 1, 1, 4, 4, 4, 7]);
});
describe("rating",()=>{it("weights facts",()=>expect(appearanceRating({goals:2,assists:1,teamId:"red"},"red")).toBe(11));it("gives losers and no-team sessions no win point",()=>{expect(appearanceRating({goals:1,assists:0,teamId:"black"},"red")).toBe(4);expect(uniqueWinningTeamId(session([],"none"))).toBeUndefined()});it("awards exactly one bonus despite multiple set wins",()=>{const s=session([4,2]);expect(uniqueWinningTeamId(s)).toBe("t0");expect(aggregateLeaderboard([s])[0].rating).toBe(1)});it("a tied result has no winner",()=>expect(uniqueWinningTeamId(session([2,2]))).toBeUndefined())});
describe("ranking",()=>{it("orders by rating",()=>{const s=session([1,0]);s.appearances[0].goals=1;expect(aggregateLeaderboard([s]).map(r=>r.name)).toEqual(["Alpha","Beta"])});it("shares visible competition ranks and uses names only for stable rendering",()=>{const s=session([0,0]);s.appearances.push({playerId:"c",playerName:"Charlie",goals:1,assists:0});s.appearances[0].goals=1;const rows=aggregateLeaderboard([s]);expect(rows.map(r=>[r.name,r.rank])).toEqual([["Alpha",1],["Charlie",1],["Beta",3]])})});
