"use client";
import { useState } from "react";
import type { Group,SessionFormat,Visibility } from "@/types/domain";
import { ActionOverlay } from "@/components/action-overlay";
import { InfoTip } from "@/components/info-tip";
import { regenerateShareTokenAction,updateGroupSettingsAction } from "@/app/app/actions";
import { WEEKDAYS } from "@/lib/format";

export function GroupSettings({group}:{group:Group}){
  const [visibility,setVisibility]=useState<Visibility>(group.visibility);
  const [format,setFormat]=useState<SessionFormat>(group.defaultSessionFormat);
  const [schedules,setSchedules]=useState(group.schedules);
  const [message,setMessage]=useState("");const [isError,setIsError]=useState(false);const [pendingLabel,setPendingLabel]=useState("");const [confirmToken,setConfirmToken]=useState(false);
  const save=async()=>{const unique=new Set(schedules.map(s=>`${s.dayOfWeek}-${s.kickoffTime}`));if(unique.size!==schedules.length){setIsError(true);setMessage("Two schedules use the same day and time.");return}setPendingLabel("Saving settings");setMessage("");try{const result=await updateGroupSettingsAction(group.id,visibility,format,schedules.map(s=>({day_of_week:s.dayOfWeek,kickoff_time:s.kickoffTime,venue:s.venue,active:s.active})));setIsError(!result.ok);setMessage(result.ok?"Settings saved.":result.error)}catch(error){console.error("Save settings failed",error);setIsError(true);setMessage("Couldn’t save settings. Try again.")}finally{setPendingLabel("")}};
  const regenerate=async()=>{setPendingLabel("Regenerating private link");setMessage("");try{const result=await regenerateShareTokenAction(group.id);setConfirmToken(false);setIsError(!result.ok);setMessage(result.ok?"Private link regenerated. The previous link no longer works.":result.error)}catch(error){console.error("Regenerate private link failed",error);setIsError(true);setMessage("Couldn’t regenerate the private link. Try again.")}finally{setPendingLabel("")}};
  const pending=Boolean(pendingLabel);
  return <div className="form-stack" aria-busy={pending}><ActionOverlay active={pending} label={pendingLabel}/>{message&&<p className={`notice ${isError?"error":""}`} role={isError?"alert":"status"}>{message}</p>}
    <fieldset disabled={pending}><legend className="field-label">Visibility</legend><label className="radio-row"><input type="radio" checked={visibility==="public"} onChange={()=>setVisibility("public")}/><span className="choice-copy"><strong>Public</strong><small>Appears in Explore with a public table.</small></span></label><label className="radio-row"><input type="radio" checked={visibility==="private"} onChange={()=>setVisibility("private")}/><span className="choice-copy"><strong>Private</strong><small>Stays out of Explore. Token sharing still works.</small></span></label>{visibility==="private"&&<p className="notice">Anonymous public access is removed as soon as this setting is saved.</p>}</fieldset>
    <fieldset disabled={pending}><legend className="field-label"><span className="with-tip">Usual format <InfoTip label="Explain football formats"><strong>No teams</strong> tracks player stats only. <strong>Fixed teams</strong> has exactly two teams and one result. <strong>Set play</strong> supports 2–8 teams and any number of mini-matches.</InfoTip></span></legend><select className="select" value={format} onChange={e=>setFormat(e.target.value as SessionFormat)}><option value="none">No teams</option><option value="fixed_teams">Fixed teams · one result</option><option value="sets">Set play · multiple teams</option></select></fieldset>
    <fieldset disabled={pending}><legend className="field-label">Weekly schedules</legend>{schedules.map(s=><div className="settings-row" key={s.id}><strong>{WEEKDAYS[s.dayOfWeek-1]}</strong><div className="button-row" style={{marginTop:10}}><select className="select" aria-label="Playing day" value={s.dayOfWeek} onChange={e=>setSchedules(all=>all.map(x=>x.id===s.id?{...x,dayOfWeek:Number(e.target.value)}:x))}>{WEEKDAYS.map((day,index)=><option key={day} value={index+1}>{day}</option>)}</select><input className="input" aria-label="Kickoff time" type="time" value={s.kickoffTime} onChange={e=>setSchedules(all=>all.map(x=>x.id===s.id?{...x,kickoffTime:e.target.value}:x))}/><input className="input" aria-label="Venue" placeholder="Venue, optional" value={s.venue??""} onChange={e=>setSchedules(all=>all.map(x=>x.id===s.id?{...x,venue:e.target.value}:x))}/></div><button className="text-link" type="button" onClick={()=>setSchedules(all=>all.filter(x=>x.id!==s.id))}>Remove</button></div>)}<button type="button" className="text-link" onClick={()=>setSchedules(all=>[...all,{id:crypto.randomUUID(),dayOfWeek:6,kickoffTime:"10:00",active:true}])}>+ Add another day</button></fieldset>
    <button className="button primary" disabled={pending} type="button" onClick={save}>Save settings</button>
    {!confirmToken?<button className="text-link" disabled={pending} type="button" onClick={()=>setConfirmToken(true)}>Regenerate private share link</button>:<div className="notice"><p>Anyone using the previous private link will lose access.</p><div className="button-row"><button className="button small" type="button" onClick={regenerate}>Regenerate link</button><button className="text-link" type="button" onClick={()=>setConfirmToken(false)}>Cancel</button></div></div>}
  </div>;
}
