"use client";
import { FormEvent,useState } from "react";
import type { Player } from "@/types/domain";
import { InlineSpinner } from "@/components/inline-spinner";
import { addPlayerAction,setPlayerActiveAction } from "@/app/app/actions";
import { BalancingProfileEditor } from "@/components/balancing-profile-editor";

export function PlayerManager({initial,groupId}:{initial:Player[];groupId:string}){
  const [players,setPlayers]=useState(initial);const [name,setName]=useState("");const [error,setError]=useState("");const [pendingLabel,setPendingLabel]=useState("");
  const add=async(e:FormEvent)=>{e.preventDefault();const clean=name.trim();if(!clean)return;setError("");setPendingLabel(`Adding ${clean}`);try{const result=await addPlayerAction(groupId,clean);if(!result.ok){setError(result.error);return}setPlayers(p=>[...p,{id:result.id,name:clean,active:true}]);setName("")}catch(error){console.error("Add player failed",error);setError("Couldn’t add the player. Try again.")}finally{setPendingLabel("")}};
  const toggle=async(player:Player)=>{setError("");setPendingLabel(`${player.active?"Deactivating":"Reactivating"} ${player.name}`);try{const result=await setPlayerActiveAction(groupId,player.id,!player.active);if(!result.ok){setError(result.error);return}setPlayers(all=>all.map(x=>x.id===player.id?{...x,active:!x.active}:x))}catch(error){console.error("Player status update failed",error);setError("Couldn’t update the player. Try again.")}finally{setPendingLabel("")}};
  const pending=Boolean(pendingLabel);return <>{error&&<p className="notice error" role="alert">{error}</p>}<form className="button-row" onSubmit={add} aria-busy={pending}><input className="input" disabled={pending} value={name} onChange={e=>setName(e.target.value)} placeholder="Player name" aria-label="Player name"/><button className="button primary small" disabled={pending||!name.trim()}>{pendingLabel.startsWith("Adding ")&&<InlineSpinner/>}Add</button></form><div className="list" style={{marginTop:24}}>{players.map(p=><div key={p.id}><div className="list-row"><div><strong>{p.name}</strong><span className="mono muted" style={{fontSize:10}}>{p.active?"Active":"Inactive"}</span></div><button className="text-link" disabled={pending} onClick={()=>toggle(p)}>{pendingLabel.endsWith(p.name)&&<InlineSpinner/>}{p.active?"Deactivate":"Reactivate"}</button></div><details><summary>Edit {p.name} balancing details</summary><BalancingProfileEditor groupId={groupId} playerId={p.id} name={p.name} initial={p.balancing} onSaved={balancing=>setPlayers(all=>all.map(x=>x.id===p.id?{...x,balancing}:x))}/></details></div>)}</div></>;
}
