"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { Group, SessionFormat } from "@/types/domain";
import { localDateInput, preferredSchedule } from "@/lib/time";
import { matchRoster } from "@/lib/roster";
import { saveSessionAction } from "@/app/app/actions";

type DraftPlayer = { id: string; name: string; selected: boolean; team: number; goals: number; assists: number; isNew?: boolean };
type Draft = { clientSessionId: string; step: number; mode: "roster"|"paste"; date: string; time: string; format: SessionFormat; players: DraftPlayer[]; paste: string; labels: string[]; wins: number[] };

function Counter({ value, setValue, label }: { value: number; setValue: (n:number)=>void; label: string }) { return <div className="stepper"><button type="button" disabled={value===0} onClick={() => setValue(Math.max(0,value-1))} aria-label={`Remove ${label}`}>−</button><output aria-label={`${label}: ${value}`}>{value}</output><button type="button" onClick={() => setValue(value+1)} aria-label={`Add ${label}`}>+</button></div>; }

export function SessionLogger({ group }: { group: Group }) {
  const router = useRouter(); const schedule = preferredSchedule(group.schedules,new Date(),group.timezone);
  const initial = useMemo<Draft>(() => ({ clientSessionId: crypto.randomUUID(), step: 1, mode:"roster", date:localDateInput(new Date(),group.timezone), time:schedule?.kickoffTime ?? "18:00", format:group.defaultSessionFormat, players:group.players.filter(p=>p.active).map(p=>({id:p.id,name:p.name,selected:false,team:0,goals:0,assists:0})),paste:"",labels:["Red","Black"],wins:[0,0] }),[group,schedule]);
  const [draft,setDraft] = useState(initial); const [ready,setReady] = useState(false); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const key = `ibpy-session-${group.id}`;
  useEffect(() => { const timer=window.setTimeout(()=>{const saved=localStorage.getItem(key);if(saved){try{setDraft(JSON.parse(saved) as Draft)}catch{localStorage.removeItem(key)}}setReady(true)},0);return()=>window.clearTimeout(timer); },[key]);
  useEffect(() => { if(ready) localStorage.setItem(key,JSON.stringify(draft)); },[draft,key,ready]);
  const selected = draft.players.filter(p=>p.selected); const steps = draft.format === "none" ? [1,3,4] : [1,2,3,4];
  const updatePlayer = (id:string, update:Partial<DraftPlayer>) => setDraft(d=>({...d,players:d.players.map(p=>p.id===id?{...p,...update}:p)}));
  const next = () => { const index=steps.indexOf(draft.step); if(index < steps.length-1) setDraft(d=>({...d,step:steps[index+1]})); };
  const back = () => { const index=steps.indexOf(draft.step); if(index>0) setDraft(d=>({...d,step:steps[index-1]})); else router.back(); };
  const parsePaste = () => { const matched=matchRoster(draft.paste,group.players); const existing=new Set(draft.players.map(p=>p.id)); const additions:DraftPlayer[]=[]; for(const row of matched){ if(row.status==="matched") updatePlayer(row.player.id,{selected:true}); else { const id=`new-${row.input.toLowerCase().replace(/\W+/g,"-")}`; if(!existing.has(id)) additions.push({id,name:row.input,selected:true,team:0,goals:0,assists:0,isNew:true}); } } setDraft(d=>({...d,players:[...d.players,...additions]})); };
  const save = async () => { setSaving(true);setError("");const result=await saveSessionAction({group_id:group.id,client_session_id:draft.clientSessionId,date:draft.date,time:draft.time,timezone:group.timezone,format:draft.format,teams:draft.format==="none"?[]:draft.labels.map((label,i)=>({client_key:String(i),label,set_wins:draft.wins[i]})),players:selected.map(p=>({...(p.isNew?{name:p.name}:{player_id:p.id}),team_key:draft.format==="none"?undefined:String(p.team),goals:p.goals,assists:p.assists}))});setSaving(false);if(!result.ok){setError(result.error);return;}localStorage.removeItem(key);router.push(`/app/groups/${group.id}/leaderboard?saved=1`); };
  const progress = `${draft.step===1?"Players":draft.step===2?"Teams":draft.step===3?"Stats":"Result"} · ${steps.indexOf(draft.step)+1} of ${steps.length}`;
  if(!ready) return <p className="empty">Loading your session draft…</p>;
  return <>
    <div className="page-head compact"><p className="eyebrow">{group.name}</p><h1>{draft.step===1?"WHO PLAYED?":draft.step===2?"PICK TEAMS":draft.step===3?"LOG THE STATS":"RECORD RESULT"}</h1></div>
    {draft.step===1 && <section>
      <div className="form-stack" style={{marginBottom:22}}><label className="field"><span className="field-label">Session date</span><input className="input" type="date" value={draft.date} onChange={e=>setDraft(d=>({...d,date:e.target.value}))}/></label><label className="field"><span className="field-label">Kickoff time</span><input className="input" type="time" value={draft.time} onChange={e=>setDraft(d=>({...d,time:e.target.value}))}/></label><label className="field"><span className="field-label">Format</span><select className="select" value={draft.format} onChange={e=>setDraft(d=>({...d,format:e.target.value as SessionFormat}))}><option value="none">No teams</option><option value="fixed_teams">One fixed-team result</option><option value="sets">Multiple sets</option></select></label></div>
      <div className="tabs"><button className={draft.mode==="roster"?"active":""} onClick={()=>setDraft(d=>({...d,mode:"roster"}))}>From roster</button><button className={draft.mode==="paste"?"active":""} onClick={()=>setDraft(d=>({...d,mode:"paste"}))}>Paste list</button></div>
      {draft.mode==="roster" ? <><div className="roster-list">{draft.players.filter(p=>!p.isNew).map(p=><label className="roster-row" key={p.id}><input type="checkbox" checked={p.selected} onChange={e=>updatePlayer(p.id,{selected:e.target.checked})}/><span className="toggle-box">✓</span><span className="roster-name">{p.name}</span></label>)}</div><p className="count">{selected.length} playing</p><div className="shortcuts"><button className="chip" onClick={()=>{ const last=new Set(group.sessions.at(-1)?.appearances.map(a=>a.playerId)??[]); setDraft(d=>({...d,players:d.players.map(p=>({...p,selected:last.has(p.id)}))}));}}>Use last session</button><button className="chip" onClick={()=>setDraft(d=>({...d,players:d.players.map(p=>({...p,selected:true}))}))}>Select all</button><button className="chip" onClick={()=>setDraft(d=>({...d,players:d.players.map(p=>({...p,selected:false}))}))}>Clear</button></div></> : <><label className="field"><span className="field-label">Paste player list</span><textarea className="textarea" value={draft.paste} onChange={e=>setDraft(d=>({...d,paste:e.target.value}))} placeholder={'1. Davidson\n2. Sean\n3. Tobi'} /></label><button className="button" type="button" onClick={parsePaste} style={{marginTop:12}}>Check names</button>{selected.length>0&&<div className="roster-list" style={{marginTop:20}}>{selected.map(p=><div className="roster-row" key={p.id}><span className="toggle-box" style={{background:"var(--color-lime)",color:"var(--color-ink)"}}>✓</span><span>{p.name}</span><span className="mono muted" style={{marginLeft:"auto",fontSize:10}}>{p.isNew?"New player":"Existing"}</span></div>)}</div>}</>}
    </section>}
    {draft.step===2 && <section><p className="lede">Tap a team beside each player. Labels can be changed.</p><div className="team-columns">{draft.labels.map((label,i)=><div className="team-column" key={i}><input className="input" aria-label={`Team ${i+1} label`} value={label} onChange={e=>setDraft(d=>({...d,labels:d.labels.map((v,n)=>n===i?e.target.value:v)}))}/>{selected.filter(p=>p.team===i).map(p=><div className="team-player" key={p.id}>{p.name}</div>)}</div>)}</div><div className="list" style={{marginTop:24}}>{selected.map(p=><label className="team-player" key={p.id}>{p.name}<select value={p.team} onChange={e=>updatePlayer(p.id,{team:Number(e.target.value)})}>{draft.labels.map((l,i)=><option value={i} key={i}>{l}</option>)}</select></label>)}</div></section>}
    {draft.step===3 && <section><p className="lede">Totals only. No goal timeline.</p>{selected.map(p=><div className="player-block" key={p.id}><h3>{p.name}</h3><div className="counter-line"><span>Goals</span><Counter label={`a goal for ${p.name}`} value={p.goals} setValue={goals=>updatePlayer(p.id,{goals})}/></div><div className="counter-line"><span>Assists</span><Counter label={`an assist for ${p.name}`} value={p.assists} setValue={assists=>updatePlayer(p.id,{assists})}/></div></div>)}</section>}
    {draft.step===4 && <section>{draft.format==="none"?<p className="notice">No team result for this session. Goals and assists will still count.</p>:draft.format==="fixed_teams"?<div className="form-stack">{draft.labels.map((label,i)=><label className="radio-row" key={i}><input type="radio" name="winner" checked={draft.wins[i]===1} onChange={()=>setDraft(d=>({...d,wins:d.wins.map((_,n)=>n===i?1:0)}))}/><span>{label} won</span></label>)}<label className="radio-row"><input type="radio" name="winner" checked={draft.wins.every(w=>w===0)} onChange={()=>setDraft(d=>({...d,wins:d.wins.map(()=>0)}))}/><span>No winner</span></label></div>:<>{draft.labels.map((label,i)=><div className="counter-line" key={i}><strong>{label}</strong><Counter label={`a set win for ${label}`} value={draft.wins[i]} setValue={value=>setDraft(d=>({...d,wins:d.wins.map((v,n)=>n===i?value:v)}))}/></div>)}</>}</section>}
    {error&&<p className="notice error" role="alert">{error}</p>}<div className="sticky-action"><button className="text-link" type="button" onClick={back}>Back</button><span className="step-progress">{progress}</span><button className="button primary" type="button" disabled={saving||(draft.step===1&&selected.length===0)} onClick={draft.step===4?save:next}>{saving?"Saving…":draft.step===4?"Save session":"Continue"}</button></div>
  </>;
}
